global:
  namespace: fullstack-dev
  environment: dev

frontend:
  replicaCount: 1
  image:
    tag: v1.0.3-dev

backend:
  replicaCount: 1
  image:
    tag: v1.0.3-dev

mysql:
  persistence:
    size: 2Gi

ingress:
  enabled: true
  className: nginx
  enableCatchAll: true
