global:
  namespace: fullstack-dev
  environment: dev

frontend:
  replicaCount: 1
  image:
    tag: v1.0.3-dev

backend:
  replicaCount: 1
  image:
    tag: v1.0.3-dev

mysql:
  persistence:
    size: 2Gi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev.fullstack.local
      paths:
        - path: /api
          pathType: Prefix
          service:
            name: backend
            port: 3000
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80
