global:
  namespace: fullstack-staging
  environment: staging

frontend:
  replicaCount: 2
  image:
    tag: staging-latest

backend:
  replicaCount: 2
  image:
    tag: staging-latest

mysql:
  persistence:
    size: 5Gi

ingress:
  enabled: true
  className: nginx
  enableCatchAll: true
