global:
  namespace: fullstack-prod
  environment: prod

frontend:
  replicaCount: 3
  image:
    tag: v1.0.4-main

backend:
  replicaCount: 3
  image:
    tag: v1.0.4-main

mysql:
  persistence:
    size: 10Gi

ingress:
  enabled: true
  className: nginx
  enableCatchAll: true
  
