global:
  namespace: fullstack-prod
  environment: prod

frontend:
  replicaCount: 3
  image:
    tag: v1.0.8-main

backend:
  replicaCount: 3
  image:
    tag: v1.0.8-main

mysql:
  persistence:
    size: 10Gi

ingress:
  hosts:
    - host: fullstack.local
