global:
  namespace: fullstack-dev
  environment: dev

frontend:
  replicaCount: 1
  image:
    tag: dev-latest

backend:
  replicaCount: 1
  image:
    tag: dev-latest

mysql:
  persistence:
    size: 2Gi

ingress:
  hosts:
    - host: dev.fullstack.local
