global:
  namespace: fullstack-prod
  environment: prod

frontend:
  replicaCount: 3
  image:
    tag: prod-latest

backend:
  replicaCount: 3
  image:
    tag: prod-latest

mysql:
  persistence:
    size: 10Gi

ingress:
  hosts:
    - host: fullstack.local
