apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-staging
  namespace: argocd
spec:
  project: fullstack-project

  source:
    repoURL: https://github.com/vinaymanjunath2001/multibranch-fullstack-cicd.git
    targetRevision: staging
    path: helm/fullstack-app
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: fullstack-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
